// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    will
    (
        init => init
        status => status
        removeInheritor => remove_inheritor
        addInheritor => add_inheritor
        claimInheritance => claim_inheritance
        addMultipleInheritors => add_multiple_inheritors
        removeMultipleInheritors => remove_multiple_inheritors
        getPerTokenInheritance => per_token_inheritance
        getInheritanceMatureUNIX => inheritance_mature_unix
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
